
version: 2

sources:
  - name: tfl
    database: "{{ env_var('DBT_DATABASE', 'tfl-data-visualization') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'tfl') }}"
    tables:
      - name: station_footfall

models:
    - name: station_footfall_daily
      description: "Aggregate by day"
      columns:
          - name: travel_date
          - name: day_of_week
          - name: station
          - name: entry_tap_count
          - name: exit_tap_count
          - name: total_tap_count
