
version: 2

sources:
  - name: tfl
    database: tfl-data-visualization # replace with your project id
    schema: tfl
    tables:
      - name: station_footfall

models:
    - name: station_footfall_daily
      description: "Aggregate by day"
      columns:
          - name: travel_date
          - name: day_of_week
          - name: station
          - name: entry_tap_count
          - name: exit_tap_count
          - name: total_tap_count
